### ISSUE TITLE
Benchmark label incorrect 

### ISSUE THREAD

**Issue by Nano1337** [facebookresearch/unibench#11]
In the file `unibench/benchmarks_zoo/benchmarks.py`, it seems like `dspr_y_position` is defined as `transfer` while it's marked as `vtab` in the associated README in `unibench/benchmarks_zoo/README.md`. What's the correct benchmark group should this eval be in?

**Comment by Nano1337** [comment]
The change has been indicated in #12

**Comment by haideraltahan** [comment]
Hi @Nano1337, great catch! Thank you for pointing that out.
This naming scheme should be deprecated in future versions, as it serve very limited purpose and some of these benchmarks can be defined as multiple categories.
