### ISSUE TITLE
Inspecting evaluation results

### ISSUE THREAD

**Issue by ethahtz** [facebookresearch/unibench#13]
Hi, I was wondering if there's a way of looking at individual benchmark on each model (e.g. I'd like to see the Winoground & coco-order performances separately for a model instead of their grouped aggregation)? Also, is there a way to read the `.f` files saved by unibench? Is there a way to save those results in json for instance? Thanks a lot!

**Comment by ethahtz** [comment]
I was able to load the files with `pandas.read_feather`!

**Comment by haideraltahan** [comment]
Hi @ethahtz,

You could also use the `OutputHandler`, for instance:

```python
from unibench.output import OutputHandler

outputhandler = OutputHandler()
outputhandler.load_all_csvs()
results = outputhandler.query(**{"benchmark_name": ['winoground', 'coco-order']})

```

The `results` variable would have pandas dataframe of the individual performance on each image in the benchmark.

Further examples are in https://github.com/facebookresearch/unibench/tree/main/figures
