### ISSUE TITLE
Dataset is not found.

### ISSUE THREAD

**Issue by PrettyMagnolia** [facebookresearch/unibench#7]
Hi,

I hope you’re doing well. I was working with the `benchmark.py` script and noticed that all the dataset references (such as `haideraltahan/wds_cifar10`、`haideraltahan/wds_food101`) appear to be missing. 

```
    raise DatasetNotFoundError(f"Dataset '{path}' doesn't exist on the Hub or cannot be accessed.") from e
datasets.exceptions.DatasetNotFoundError: Dataset 'haideraltahan/wds_food101' doesn't exist on the Hub or cannot be accessed.
```

I tried searching for the haideraltahan repository on Hugging Face but couldn’t locate the mentioned datasets. Could you kindly point me to the correct repository or provide guidance on where to find these datasets? I’d greatly appreciate your assistance.

Thank you for your time and help!

**Comment by hazirbas** [comment]
@haideraltahan is this (https://huggingface.co/datasets/clip-benchmark/wds_food101) the original source of the dataset?

**Comment by PrettyMagnolia** [comment]
I viewed this benchmark and found that some datasets supported by Unibench are not in clip-benchmark, such as  vg_relation, vg_attribution.

> @haideraltahan is this (https://huggingface.co/datasets/clip-benchmark/wds_food101) the original source of the dataset?

**Comment by haideraltahan** [comment]
Hi @PrettyMagnolia,

Thank you for highlighting the issue with loading some datasets, we are currently working on a solution.

**Comment by haideraltahan** [comment]
@PrettyMagnolia, I believe the issue has been resolved. Please open it back if the issue still persist

**Comment by PrettyMagnolia** [comment]
> @PrettyMagnolia, I believe the issue has been resolved. Please open it back if the issue still persist

Ok, thanks a lot！
