### ISSUE TITLE
No local evaluation is happening

### ISSUE THREAD

**Issue by chaitanyakrishna1248** [facebookresearch/unibench#9]
Hi,

I was trying to evaluate some of the models but every time it downloads precomputed results instead of evaluating locally even though I am setting the flag to false. Any idea how to resolve this?

**Comment by haideraltahan** [comment]
Hi @chaitanyakrishna1248,

This is related to some evaluate benchmarks not being available on huggingface (similar to issue #7). We are currently working on a solution and will be posting any update on #7.
